# Generated by Django 5.2.3 on 2025-10-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interviewschedule_additional_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
