# Generated by Django 5.2.3 on 2025-10-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentprofile_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
